# Generated by Django 4.1.1 on 2022-10-03 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='videos_image/')),
                ('video', models.FileField(upload_to='video_file/')),
                ('views', models.BigIntegerField(default=0, editable=False)),
                ('likes', models.BigIntegerField(default=0, editable=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('chanel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chanel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
