# Generated by Django 4.1.1 on 2022-10-07 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
