# Generated by Django 4.1.1 on 2022-10-27 05:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0002_video_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.ManyToManyField(related_name='user_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
