# Generated by Django 4.1.2 on 2022-10-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_remove_video_user_video_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.BigIntegerField(default=0),
        ),
    ]
