# Generated by Django 4.1.2 on 2022-10-30 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_remove_video_likes_videoviews_videocomment_postlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='views',
        ),
    ]
