# Generated by Django 4.1.2 on 2022-10-30 14:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0007_remove_video_views'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostLikes',
            new_name='VideoLikes',
        ),
    ]
