# Generated by Django 4.1.2 on 2022-11-07 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_videodislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
