# Generated by Django 4.1.1 on 2022-10-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_site', models.CharField(max_length=50)),
                ('logo_site', models.ImageField(upload_to='logo/')),
                ('description_site', models.TextField()),
                ('email_site', models.EmailField(max_length=254)),
                ('instagram_site', models.URLField()),
                ('phone', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
